name: 'node18'
description: 'For running npm and node'

inputs:
  function:
    description: 'function to run'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /bin/bash
  args:
    - -c
    - |
      source .scripts/cicd/jobs.sh
      ${{ inputs.function }}