name: 'Run JS Script in Node'
description: 'Runs a script using the node container'

inputs:
  script:
    description: 'Path to the script'
    required: true

runs:
  using: 'docker'
  image: 'node:20'
  args:
    - ${{ inputs.script }}