name: 'Wasm'
description: 'Build web assembly'

inputs:
  function:
    description: 'function to run'
    required: true

runs:
  using: 'docker'
  image: 'youone/dspdf-wasm'
  entrypoint: /bin/bash
  args:
    - -c
    - |
      source .scripts/cicd/jobs.sh
      ${{ inputs.function }}